# 設定ファイルをリロードする
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# tmuxを256色表示できるようにする
set -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'
set -g history-limit 50000

# 番号基準値を変更
set -g base-index 1

# ----------------------------------------
# Window
# ----------------------------------------
bind \ split-window -h  # \ でペインを縦分割
bind - split-window -v  # - でペインを横分割

# ----------------------------------------
# Mouse
# ----------------------------------------
setw -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

# ----------------------------------------
# Copy
# ----------------------------------------
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key C-p paste-buffer  # 'C-p'でペースト

# ----------------------------------------
# ステータスバー
# ----------------------------------------
set -g status-position top
set -g status-left-length 90
set -g status-right-length 90
set -g status-interval 1
set -g status-justify centre
set -g status-left '#H:[#P]'
set -g status-right '#(wifi) #(battery --tmux) [%Y-%m-%d(%a) %H:%M:%S]'
# ステータスバーの色設定
set -g status-bg "colour55"
set -g status-fg "colour255"

