# 設定ファイルをリロードする
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# tmuxを256色表示できるようにする
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'
set -g history-limit 50000

# | でペインを縦分割、- でペインを横分割する
bind \ split-window -h
bind - split-window -v

# 番号基準値を変更
set-option -g base-index 1

# マウス操作を有効にする
set-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

# コピーモードを設定する
# コピーモードでvimキーバインドを使う
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# 'C-p'でペースト
bind-key C-p paste-buffer

# ステータスバーの設定
set-option -g status-position top
set-option -g status-left-length 90
set-option -g status-right-length 90
set-option -g status-interval 1
set-option -g status-justify centre
set-option -g status-left '#H:[#P]'
set-option -g status-right '#(wifi) #(battery --tmux) [%Y-%m-%d(%a) %H:%M]'

