#!/bin/sh
# Create a memo file with the current date.
# Usage: mkmemo [directory]
#   directory: The directory to create the memo file. (default: .)
# Example: mkmemo ~/memo
#   Create a memo file in ~/memo/$(date +%Y)/$(date +%Y-%m-%d).
# Example: mkmemo
#   Create a memo file in ./$(date +%Y)/$(date +%Y-%m-%d).
file="${1:-.}/$(date +%Y)/$(date +%Y%m%d).md"
mkdir -p $(dirname $file)
if [ -e $file ]; then
  echo "File exists. ($file)"
  exit 1
fi
touch $file
echo "# $(date +%Y-%m-%d)" > $file
echo "Created $file"
