#!/bin/sh
year=$(date +%Y)
mkdir -p $year
file=$year/$(date +%Y%m%d).md
if [ -e $file ]; then
  echo "File exists. ($file)"
  exit 1
fi
touch $file
echo "# $(date +%Y-%m-%d)" > $file
echo "Created $file"
