# ~/.config/starship.toml
add_newline = false

[character]      # The name of the module we are confguring is "character"
symbol = "➜"     # The "symbol" segment is being set to "➜"

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "👿"
[[battery.display]]  # バッテリー残量が0％〜30％の間は「太字の赤色」スタイルを利用する
threshold = 30
style = "bold red"
[[battery.display]]  # バッテリー残量が31％〜60％の間は「太字の黄色」スタイルを利用する
threshold = 60
style = "bold yellow"
[[battery.display]]  # バッテリー残量が61％〜100％の間は「太字の緑色」スタイルを利用する
threshold = 100
style = "bold blue"

[directory]
truncation_length = 8

[git_branch]
symbol = "🌱 "

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged = "➕"
renamed = "👅"
deleted = "🗑"

[time]
disabled = true
format = "[%T]"
utc_time_offset = -9

[username]
show_always = true