[settings]
idiomatic_version_file_enable_tools = []
python.uv_venv_auto = true
experimental = true

[tools]
#----Core tools----
node = "lts"
go = "latest"

#----Python----
python = "3.11"
# python = "miniconda3-latest"
uv = "latest"
ruff = "latest"

#----AI agents----
"npm:@openai/codex" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "2.1.112"
# "npm:@github/copilot" = "latest"

#----command line tools----
aws-cli = "latest"
bat = "latest"
eza = "latest"
gh = "latest"
ghq = "latest"
fzf = "latest"

#----nvim----
neovim = "latest"
rg = "latest"
fd = "latest"

lazygit = "latest"
"npm:czg" = "latest"
"npm:cz-git" = "latest"
