[settings]
idiomatic_version_file_enable_tools = []

[tools]
# Core tools
node = "24"
python = "3.11"

"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"

uv = "latest"
ruff = "latest"
